# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: new page for tc.ice
email: tan.chao.hawk@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
    tc and ice have a baby now, tc decided to mark some memories here or elsewhere
    so we will see.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tanchao.github.io" # the base hostname & protocol for your site
weibo_username: _tanchao_
github_username: tanchao 

# refer to http://yansu.org/2014/02/12/how-to-deploy-a-blog-on-github-by-jekyll.html
permalink: /:year/:month/:day/:title.html
paginate: 10
author:
  name: tanchao


# Build settings
markdown: kramdown
